[package]
name = "torrenthealer"
version = "0.1.0"
edition = "2021"

[dependencies]
bendy = "0.3.3"
mainline = { version = "2.0.1", features = ["async"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
